= asciidoc-likbez

Это ликбез по языку разметки AsciiDoc.

https://en.wikipedia.org/wiki/AsciiDoc

https://ru.wikipedia.org/wiki/AsciiDoc


== Заголовки разделов документа

Примеры заголовков.
....
= Заголовок статьи/документа (Уровень 0)

== Заголовок параграфа/раздела (Уровень 1)

=== Заголовок подраздела (Уровень 2)

==== Заголовок подраздела (Уровень 3)

===== Заголовок подраздела (Уровень 4)

====== Заголовок подраздела (Уровень 5)

== Заголовок нового параграфа/раздела (Уровень 1)
....

WARNING: _Заголовок Уровня 0_ может быть только один в документе типа *article*, а в документах типа *book* количество _Заголовков Уровня 0_ может быть больше одного. По умолчанию задан тип документа *article*.

NOTE: Подробнее про заголовки разделов документа см. в разделе https://docs.asciidoctor.org/asciidoc/latest/sections/titles-and-levels/[Section Titles and Levels] документации проекта asciidoctor.


== Абзацы

Абзацы - блоки текста, отделенные друг от друга пустыми строками.

.Пример 1 - два обычных абзаца
....
Обычный абзац с текстом начинается без отсупа (не с символа пробела). Содержит от одого символа, слова, предложения до нескольких. 

Чтобы начать новый абзац, нужно отделить новый текст от предыдущего текста пустой строкой.
....

Результат Примера 1:
====
Обычный абзац с текстом начинается без отсупа (не с символа пробела). Содержит от одого символа, слова, предложения до нескольких. 

Чтобы начать новый абзац, нужно отделить новый текст от предыдущего текста пустой строкой.

====

